# restful: true #=> [index, show] -> public; [new, create, edit, update, destroy] -> right

# Verfügbare rechte:
# public - jeder hat zugriff
# member - Allclansneed Mitglieder
# site   - Mitglied auf der Seite
# right  - Man muss das Recht auf der Seite besitzen

article:
  restful: true
clanwar:
  restful: true
clanwar_screenshots:
  default: site
clans:
  default: member
classifieds:
  restful: true
comments:
    default: member
event:
  restful: true
  showDay: public
forum:
  restful: true
forum_message:
  default: member
forum_thread:
  restful:true
  new: member
  create: member
friends:
  default: member
  index: public
gallery:
  restful: true
gallery_pic:
  restful: true
groups: 
  default: member
  index: public
  show: public
guestbook:
  default: public
  destroy: right
  add_comment: site
login:
  default: public
messages:
  default: member
navigation:
  default: right
news:
  restful: true
  default: right
pages:
  restful: true
poll:
  restful: true
  show: member
  vote: member
profile:
  restful: true
  start: member
  new: public
  create: public
rating:
  default: member
shoutbox:
  restful: true
squad:
  default: member
squad_user:
  default: member
template_boxes:
  default: right
templates:
  default: right
ticket_message:
  default: member
tickets:
  default: member
  destroy: right