d01:
  link: "#540404"
  linkhover: "black"
  defaultcolor: "#eee"
  dark: "white"
  light: "#ccc"
  verylight: "#888"
  lightbackground: "#777"
  bordercolor: "#540404"
  bottomborder: "#888"
d02:
  link: "#03617A"
  linkhover: "#000"
  defaultcolor: "black"
  dark: "black"
  light: "#ddd"
  verylight: "#ddd"
  lightbackground: "#eee"
  bordercolor: "#6678B1"
  bottomborder: "#ccc"
d03:
  main: ""
d04:
  main: ""
d05:
  link: "#a4e05b"
  linkhover: "black"
  defaultcolor: "#eee"
  dark: "white"
  light: "#ccc"
  verylight: "#aaa"
  lightbackground: "#777"
  bordercolor: "#a4e05b"
  bottomborder: "#888"
d06:
  main: ""
d07:
  link: "#540404"
  linkhover: "black"
  defaultcolor: "black"
  dark: "black"
  light: "#666"
  verylight: "#aaa"
  lightbackground: "#ccc"
  bordercolor: "#540404"
  bottomborder: "#888"
d08:
  link: "#03617A"
  linkhover: "#000"
  defaultcolor: "black"
  dark: "black"
  light: "#ccc"
  verylight: "#ddd"
  lightbackground: "#eee"
  bordercolor: "#6678B1"
  bottomborder: "#ccc"
d09:
  link: "#2e5002"
  linkhover: "black"
  defaultcolor: "black"
  dark: "black"
  light: "#666"
  verylight: "#aaa"
  lightbackground: "#ccc"
  bordercolor: "#2e5002"
  bottomborder: "#bbb"
d10:
  main: ""
d11:     
  main: ""
d12:
  link: "#9d281b"
  linkhover: "black"
  defaultcolor: "white"
  dark: "white"
  light: "#666"
  verylight: "#aaa"
  lightbackground: "#888"
  bordercolor: "#9d281b"
  bottomborder: "#555"
d13:
  link: "#03617A"
  linkhover: "#000"
  defaultcolor: "black"
  dark: "black"
  light: "#888"
  verylight: "#ddd"
  lightbackground: "#eee"
  bordercolor: "#6678B1"
  bottomborder: "#ccc"
d14:
  main: ""
d15:
  link: "#03617A"
  linkhover: "#000"
  defaultcolor: "black"
  dark: "black"
  light: "#888"
  verylight: "#ddd"
  lightbackground: "#eee"
  bordercolor: "#6678B1"
  bottomborder: "#efefef"