class AddIndexesToAllTables < ActiveRecord::Migration
  def self.up
    add_index :articles, :user_id
    add_index :articles, :site_id
    add_index :articles, :commentable_id
    add_index :categories, :site_id
    add_index :clan_join_inquiries, :clan_id
    add_index :clan_join_inquiries, :user_id
    add_index :clans, :site_id
    add_index :clans, :owner_id
    add_index :clanwar_maps, :clanwar_id
    add_index :clanwar_screenshots, :clanwar_id
    add_index :clanwar_screenshots, :user_id
    add_index :clanwars, :squad_id
    add_index :clanwars, :site_id
    add_index :clanwars, :user_id
    add_index :classifieds, :user_id
    add_index :classifieds, :site_id
    add_index :comments, :user_id
    add_index :comments, :site_id
    add_index :comments, :commentable_id
    add_index :components, :parent_id
    add_index :events, :expire_at
    add_index :events, :site_id
    add_index :forum_messages, :user_id
    add_index :forum_messages, :forum_thread_id
    add_index :forum_messages, :site_id
    add_index :forum_threads, :user_id
    add_index :forum_threads, :site_id
    add_index :forum_threads, :threadable_id
    add_index :forums, :site_id
    add_index :forums, :parent_id
    add_index :forums, :intern
    add_index :friendships, :user_id
    add_index :friendships, :friend_id
    add_index :galleries, :user_id
    add_index :galleries, :site_id
    add_index :galleries, :intern
    add_index :gallery_pics, :site_id
    add_index :gallery_pics, :user_id
    add_index :gallery_pics, :gallery_id
    add_index :gallery_pics, :intern
    add_index :games_squads, :game_id
    add_index :games_squads, :squad_id
    add_index :groupmemberships, :group_id
    add_index :groupmemberships, :user_id
    add_index :groups, :founder_id
    add_index :guestbooks, :comment_author_id
    add_index :guestbooks, :site_id
    add_index :messages, :sender_id
    add_index :messages, :receiver_id
    add_index :moderators, :user_id
    add_index :moderators, :site_id
    add_index :moderators, :forum_id
    add_index :navigations, :template_box_id
    add_index :navigations, :navigation_template_id
    add_index :navigations, :site_id
    add_index :news, :site_id
    add_index :news, :user_id
    add_index :news, :category_id
    add_index :pages, :site_id
    add_index :pages, :user_id
    add_index :pages, :navigation_id
    add_index :pinwalls, :user_id
    add_index :poll_options, :poll_id
    add_index :poll_results, :poll_id
    add_index :poll_results, :user_id
    add_index :poll_results, :poll_option_id
    add_index :polls, :site_id
    add_index :polls, :user_id
    add_index :profiles, :user_id
    add_index :ratings, :rateable_id
    add_index :ratings, :user_id
    add_index :right_components, :user_right_id
    add_index :right_components, :component_id
    add_index :shoutboxes, :user_id
    add_index :shoutboxes, :site_id
    add_index :sites, :template_id
    add_index :sites, :owner_id
    add_index :squad_users, :squad_id
    add_index :squad_users, :user_id
    add_index :squads, :clan_id
    add_index :taggings, :taggable_id
    add_index :tags, :site_id
    add_index :template_areas, :template_id
    add_index :template_areas, :prefered_box_type_id
    add_index :template_box_types, :component_id
    add_index :template_boxes, :template_area_id
    add_index :template_boxes, :template_box_type_id
    add_index :ticket_messages, :user_id
    add_index :ticket_messages, :ticket_id
    add_index :tickets, :admin_id
    add_index :tickets, :author_id
    add_index :tickets, :status_id
    add_index :tickets, :category_id
    add_index :tickets, :site_id
    add_index :user_rights, :site_id
    add_index :user_rights, :user_id
  end

  def self.down
    remove_index :user_rights, :user_id
    remove_index :user_rights, :site_id
    remove_index :tickets, :site_id
    remove_index :tickets, :category_id
    remove_index :tickets, :status_id
    remove_index :tickets, :author_id
    remove_index :tickets, :admin_id
    remove_index :ticket_messages, :ticket_id
    remove_index :ticket_messages, :user_id
    remove_index :template_boxes, :template_box_type_id
    remove_index :template_boxes, :template_area_id
    remove_index :template_box_types, :component_id
    remove_index :template_areas, :prefered_box_type_id
    remove_index :template_areas, :template_id
    remove_index :tags, :site_id
    remove_index :taggings, :taggable_id
    remove_index :squads, :clan_id
    remove_index :squad_users, :user_id
    remove_index :squad_users, :squad_id
    remove_index :sites, :owner_id
    remove_index :sites, :template_id
    remove_index :shoutboxes, :site_id
    remove_index :shoutboxes, :user_id
    remove_index :right_components, :component_id
    remove_index :right_components, :user_right_id
    remove_index :ratings, :user_id
    remove_index :ratings, :rateable_id
    remove_index :profiles, :user_id
    remove_index :polls, :user_id
    remove_index :polls, :site_id
    remove_index :poll_results, :poll_option_id
    remove_index :poll_results, :user_id
    remove_index :poll_results, :poll_id
    remove_index :poll_options, :poll_id
    remove_index :pinwalls, :user_id
    remove_index :pages, :navigation_id
    remove_index :pages, :user_id
    remove_index :pages, :site_id
    remove_index :news, :category_id
    remove_index :news, :user_id
    remove_index :news, :site_id
    remove_index :navigations, :site_id
    remove_index :navigations, :navigation_template_id
    remove_index :navigations, :template_box_id
    remove_index :moderators, :forum_id
    remove_index :moderators, :site_id
    remove_index :moderators, :user_id
    remove_index :messages, :receiver_id
    remove_index :messages, :sender_id
    remove_index :guestbooks, :site_id
    remove_index :guestbooks, :comment_author_id
    remove_index :groups, :founder_id
    remove_index :groupmemberships, :user_id
    remove_index :groupmemberships, :group_id
    remove_index :games_squads, :squad_id
    remove_index :games_squads, :game_id
    remove_index :gallery_pics, :intern
    remove_index :gallery_pics, :gallery_id
    remove_index :gallery_pics, :user_id
    remove_index :gallery_pics, :site_id
    remove_index :galleries, :intern
    remove_index :galleries, :site_id
    remove_index :galleries, :user_id
    remove_index :friendships, :friend_id
    remove_index :friendships, :user_id
    remove_index :forums, :intern
    remove_index :forums, :parent_id
    remove_index :forums, :site_id
    remove_index :forum_threads, :threadable_id
    remove_index :forum_threads, :site_id
    remove_index :forum_threads, :user_id
    remove_index :forum_messages, :site_id
    remove_index :forum_messages, :forum_thread_id
    remove_index :forum_messages, :user_id
    remove_index :events, :site_id
    remove_index :events, :expire_at
    remove_index :components, :parent_id
    remove_index :comments, :commentable_id
    remove_index :comments, :site_id
    remove_index :comments, :user_id
    remove_index :classifieds, :user_id
    remove_index :classifieds, :site_id
    remove_index :clanwars, :user_id
    remove_index :clanwars, :site_id
    remove_index :clanwars, :squad_id
    remove_index :clanwar_screenshots, :user_id
    remove_index :clanwar_screenshots, :clanwar_id
    remove_index :clanwar_maps, :clanwar_id
    remove_index :clans, :owner_id
    remove_index :clans, :site_id
    remove_index :clan_join_inquiries, :user_id
    remove_index :clan_join_inquiries, :clan_id
    remove_index :categories, :site_id
    remove_index :articles, :commentable_id
    remove_index :articles, :site_id
    remove_index :articles, :user_id
  end
end
